server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Angular Router — alle unbekannten Pfade → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Statische Assets mit Cache-Header
    location ~* \.(js|css|png|jpg|ico|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
