// Writes src/environments/version.ts with the git commit and build time.
// In CI these come from the GIT_SHA / BUILD_TIME env vars (the frontend image
// builds inside Docker without git); locally they fall back to git and now.
import { writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

function localSha() {
  try {
    return execSync('git rev-parse --short HEAD', { stdio: ['ignore', 'pipe', 'ignore'] })
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
}

const sha = (process.env.GIT_SHA || localSha() || 'unknown').slice(0, 7);
const buildTime = process.env.BUILD_TIME || new Date().toISOString();

const content = `// Generated by scripts/gen-version.mjs at build time. Do not edit.
export const version = {
  gitSha: ${JSON.stringify(sha)},
  buildTime: ${JSON.stringify(buildTime)},
} as const;
`;

const target = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'environments', 'version.ts');
writeFileSync(target, content);
console.log(`[gen-version] ${sha} @ ${buildTime}`);
